### ISSUE TITLE
new feature - tracer

### ISSUE THREAD

**Issue by nmizukami** [ESCOMP/mizuRoute#167]
**Goal:** 
to enable to trace DOC/DON (or other constituents) from land models

**Urgency:** 
months to a year

**Background:** 
Use advection-dispersion equation 
dC/dt = -U*dC/dx + D*d2C/dx2 + source + in-stream_process
where C = concentration [M/L3], U = velocity [L/T], D=dispersion coefficient [L2/T]
1st term in LHS = advection
2nd term in LHS = dispersion

**Tasks:**
- [ ] #536
- [x] create (copy and paste) constituent input routine 

- [x] copy current numerical routine used dfw_route.f90 into new module
Currently U and D are wave celerity and diffusivity computed for diffusive wave equation.
Currently this use fully implicit method (but can be easily changed to Crank–Nicolson (discretization  weight ==0.5) or explicit (discretization weights ==0).
- [x] Create subroutine (call base_advect_diffusion subroutine) 
U and D are input argument.
discretization weights are optional arguments
- [x] implement advection routine
- [x] implement diffusion routine
- [x] implement advection-diffusion routine
- [x] insert and test this routine in dfw_route.f90 
Check if the new routine reproduces the current routine.
- [x] Create tracer.f90 (similar to dfw_routine.f90)

**Relevant issues:** 
#153
ESCOMP/CTSM#1216

**Comment by ekluzek** [comment]
Note another desired use of this capability is for water isotope tracers needed for example in Paleo work.

**Comment by nmizukami** [comment]
stand-alone tracer (only route one constituent or solute) works for standalone use. For CESM coupling run, I am not sure when (or if) DOC can be passed from mizuRoute. So close
